name: juegos_arq
description: "A new Flutter project."
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  date_count_down: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  supabase_flutter: ^2.6.0
  url_launcher: ^6.3.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: Telemarines
      fonts:
        - asset: fonts/telemarines.ttf
